### ISSUE TITLE
Enable students to view the grades

### ISSUE THREAD

**Issue by Vreddy27** [Vreddy27/EMU-COSC381-Project#1]
**User Story**
As a student, I want to be able to view my grades online so that I can track my academic performance and identify areas for improvement.

**Detailed Description**
The students need a feature where they can access their grades through an online platform. This feature will provide them with a convenient way to monitor their academic progress which helps them in identifying areas for improvement.

**Task List**

- [ ] Develop a secure online portal for students to access grades.
- [ ] Integrate the grading system with the online portal.
- [ ] Ensure a user-friendly interface for easy grade checking.

**Acceptance Criteria**

- Students can only log in to the online portal using the Chrome browser.
- Students have to login with their credentials to check grades.
- Students will have to check the rubric for the details if any points were deducted.

**Acceptance Tests**

1. Can check the mean grade for the entire class.
2. Students can check the total grade they have in the class.
3. Attempt to log in using browsers other than Chrome and verify that access is restricted.
